### ISSUE TITLE
custom styling :)

### ISSUE THREAD

**Issue by swyxio** [rohitpotato/svelte-command-palette#1]
i bet you knew this was coming :)

i'd love to style things with tailwind and/or css variables.

**Comment by rohitpotato** [comment]
haha yes, this is on my radar for the next version.  I'd prefer CSS variables since not everyone is accustomed to using tailwind CSS. WDYT? Also would love to discuss strategies for styling.

**Comment by DevParapalli** [comment]
I think the styling could be done in 2 methods, 

1. You could give it a object named themeColors with keys denoting the various colours, passed as a prop to the component. This would allow simple colour tweaks. only keys found in themeColors would be overidden, leaving the rest as it is. 

3. You can provide a object name themeClasses, taking precedence over 1. This would allow you to change the look and feel of the entire component. only keys found in themeClasses would be overridden, leaving the rest of the styles as it is. Would allow for more finer control, being able to pass classes for the individual elements gives greater control, so stuff like hover states, outlines and the like can be controlled.

**Comment by rohitpotato** [comment]
@sw-yx @DevParapalli  

**Added custom styling** 🙂

I will merge this after a bit more testing, check out the preview: https://svelte-command-palette-git-rohitkashyap-add-164f0c-rohitpotato.vercel.app/

Supports tailwind CSS and style attributes for full control.

Refer to the styling section in the docs to see available props. 

Will appreciate some feedback on the API.

Thanks!

**Comment by rohitpotato** [comment]
Custom styling is now live, closing this.

**Comment by sw-yx** [comment]
whoops sorry just saw this - awessome!!! keeping on my radar for sure, thanks for the new feature!
