### ISSUE TITLE
delayed registration of actions

### ISSUE THREAD

**Issue by sw-yx** [rohitpotato/svelte-command-palette#19]
hi! finally got around to exploring using this :)

right now all actions must be defined up front with defineActions. this creates a centralized monster file that has all the things.

what if we could `registerAction` and `deregisterAction`? this would help break up the files to colocate them with the routes where they are applicable

**Comment by rohitpotato** [comment]
hey thanks for this! This sounds legit. Can you maybe share a spec for this that you have in mind?

**Comment by sw-yx** [comment]
something like this

```svelte
<script>
    import { registerAction } from 'svelte-command-palette'

	const act1 = registerAction({
            title: "temporary action",
            subTitle: "This action is only registered when its associated component is rendered",
            onRun: () => {/* ... */}
            shortcut: "Space k"
      })
</script>

<div use:act1 />
```

when that div mounts, it registers, when unmount, it deregisters.

`registerAction` takes either single object or array of objects

btw we might want to change the name since this conflicts with the Svelte concept of "action"

**Comment by sw-yx** [comment]
## idea 2

```svelte
<!--  SomeComponent.svelte -->
<script type="module">
    import { defineAction } from 'svelte-command-palette'

	// note the `export` keyword
	export const act1 = defineAction({
            title: "dynamically registered action",
            subTitle: "This action is only registered when its associated component is rendered",
            onRun: () => {/* ... */}
            shortcut: "Space k"
      })
</script>

<!-- works similarly to the above if you want it dynamically registered -->
<div use:act1 />

<!-- but here's the twist -->
<!--  rootlayout.svelte -->
<script>
    import { registerActions } from 'svelte-command-palette'
	import { act1 } from './SomeComponent.svelte'

	// statically register action upfront
	registerActions([act1])
</script>
```

**Comment by rohitpotato** [comment]
Thanks for the spec, I am currently stuck with work things, but I'll take a look soon. If you want to give it a shot, that'd be great too!

**Comment by rohitpotato** [comment]
@sw-yx I'm afraid I dont really understand this approach, how does exporting actions from one component and registering it in layout make lazy registration?

Also, relying on HTML nodes to register actions doesn't seem very clean to me.

In the meanwhile, you can use the `paletteStore` to dynamically add actions when needed.

Example:


```
	paletteStore.update((store) => {
		return {
			...store,
			commands: [
				...store.commands,
				{
					title: 'some new action',
					...
				}
			]
		};
	});
```

Refer to: https://svelte-command-palette.vercel.app/docs/palette-store

**Comment by sw-yx** [comment]
not currently exploring this rn so will just close for time being
