### ISSUE TITLE
This package misbehaves in Windows systems

### ISSUE THREAD

**Issue by onderbakirtas** [rohitpotato/svelte-command-palette#2]
Hi there, thanks in advance for this great package. I have encountered an issue where pressing default key combination (here `Ctrl + K`) also focuses browsers (tested in Chrome, Edge and Firefox) address bar with search.

**Comment by rohitpotato** [comment]
@onderbakirtas thanks for bringing this to my attention. I didn't test aggressively on windows system since I don't own one. Need to find a way to do this. I'll post updates.

Also, please feel free to suggest any approaches that you think can help. 

Thanks!

**Comment by rohitpotato** [comment]
This should be fixed by now, can you please confirm once?

**Comment by onderbakirtas** [comment]
> This should be fixed by now, can you please confirm once?

I will do it when I get my hands on the computer.

**Comment by rohitpotato** [comment]
@onderbakirtas were you able to test?

**Comment by onderbakirtas** [comment]
> @onderbakirtas were you able to test?

Yes I was, it was fine and working as intended. Thanks.
