### ISSUE TITLE
📝 Syntax errors in readme- unterminated string and incorrect action property

### ISSUE THREAD

**Issue by jercle** [rohitpotato/svelte-command-palette#4]
Looking at the action type: 
-  `id` should be `actionId` and `subTitle` starts with a single quote but ends with a double quote.
Also, removing comma at end of line 42

https://github.com/rohitpotato/svelte-command-palette/blob/64ad2dbe6480c38d4adf3b13bb5133b1c16736dd/README.md?plain=1#L36-L46

**Comment by rohitpotato** [comment]
merged @jercle
