### ISSUE TITLE
Adjusting height for less than 3 items in the command palette

### ISSUE THREAD

**Issue by raghavkanwal** [rohitpotato/svelte-command-palette#7]
The height of the `<div id="wrapper">` is always set to be `100vh`. This doesn't work when there's only one or two available options in the palette since the box-shadow of the container still remains at the same height. 

<img width="691" alt="Screenshot 2022-07-23 at 12 46 59 PM" src="https://user-images.githubusercontent.com/5167823/180594886-014f990b-d3ea-4592-a8b4-e7403dd2c8b3.png">

PR #6 changes this to property to `max-height` instead which can accomodate for such cases.

PS. @rohitpotato Sorry for the delay in responding, I look at Open Source projects on the weekends :P

**Comment by rohitpotato** [comment]
@raghavkanwal You are correct but this decreases the height of the **wrapper** , I think this needs to affect the command palette div only. 

The reason is if we decide to give a background blend (a tint for example), this height will affect that tint too.

**Comment by raghavkanwal** [comment]
I agree, this changes the height of the wrapper, which is the parent element.
Instead, we can add `height: fit-content` to the class `paletteWrapper` inside of `#wrapper`. That doesn't affect the parent element and still has the desired output. 
I've created a new PR, #8 for this change.

**Comment by rohitpotato** [comment]
Merged
